config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  post 'top/create' => 'top#create'
  get 'top/download' => 'top#download'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  http_basic_authenticate_with name: "mkwk", password: "Id5sH4Sj", except: :hoge
  require 'open-uri'
  require 'nokogiri'
  require 'kconv'
  require 'csv'

  def index
    @file_path = params[:file_path]
    @csv_data = read_csv(@file_path) if @file_path.present?
  end

  def create
    results = []
    url_lines = params.permit(:url_list)[:url_list]
    url_lines.each_line do | line |
      results << get_meta(line.chomp)
    end

    file_name = "/tmp/#{SecureRandom.hex(12)}.csv"
    csv_data = CSV.open(file_name, "wb") do |csv|
      csv_column_names = ["URL","TITLE","DESCRIPTION"]
      csv << csv_column_names
      results.each do | result |
        csv_column_values = [
          "#{result[:url]}",
          "#{result[:title]}",
          "#{result[:description]}",
        ]
        csv << csv_column_values
      end
    end
    redirect_to root_path(file_path: file_name)
  end

  def download
    file_path = params[:file_path]
    file_path = Rails.root.join(file_path)
    stat = File::stat(file_path)
    send_file(file_path, :length => stat.size)
  end
  private
  def get_meta(url)
    Rails.logger.info("■■■■■■■■■■before■■■■■■■■■■■")
    Rails.logger.info(url)
    Rails.logger.info("■■■■■■■■■■start■■■■■■■■■■■")
    # agent = Mechanize.new
    title = nil
    description = nil
    begin
      html = open(url, "r:binary").read
      doc = Nokogiri::HTML(html.toutf8, nil, 'utf-8')
      # doc = Nokogiri::HTML(open(url), nil, 'CP932')
      title = doc.title
      description = doc.xpath('/html/head/meta[@name="description"]/@content').to_s
    rescue Mechanize::ResponseCodeError => e
      # puts e.page.body
      title = e.to_s
      description = ""
    rescue => e
      Rails.logger.error(e.backtrace)
      title = 'error'
      description = 'error'
    end
    Rails.logger.info("■■■■■■■■■■end■■■■■■■■■■■")
    {url: url, title: title, description: description}
  end

  def read_csv(file_path)
    results = []
    CSV.foreach(file_path, headers: true) do |data|
      results << {url: data['URL'], title: data['TITLE'], description: data['DESCRIPTION']}
    end
    results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetMeta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/top/index.html.erb
<% if !@csv_data.present? %>
  <%= form_tag 'top/create', method: :post do %>
    <div class="form-group">
      <label for="url_list" class="control-label">URLを入力（複数の場合は1行1URL）</label>
      <%= text_area_tag 'url_list','', class: 'form-control', rows: 20 %>
    </div>
    <div class="text-right">
      <%= submit_tag 'TitleとDescription取得', class: 'btn btn-primary btn-lg' %>
    </div>
  <% end %>
<% else %>
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th class="w-25">URL</th>
          <th class="w-25">TITLE</th>
          <th class="w-50">DESCRIPTION</th>
        </tr>
      </thead>
      <tbody>
        <% @csv_data.each do |data| %>
          <tr>
            <td class="w-25"><%= data[:url] %></td>
            <td class="w-25"><%= data[:title] %></td>
            <td class="w-50"><%= data[:description] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="text-right">
    <%= link_to :root, class: 'btn btn-lg btn-outline-dark' do %>
      戻る
    <% end %>
    <%= link_to top_download_path(file_path: @file_path), target: :_blank, class: 'btn btn-lg btn-outline-success' do %>
      CSVダウンロード
    <% end %>
  </div>
<% end %>